[숫자 야구 게임] 무 미션 제출합니다.
REVENGE-WOOTECO/javascript-baseball-precourse pull request #5
Opened 2021-11-29 15:03 UTC by veggie-garden

안녕하세요!  
  
우선 취준 중이라 바쁘신 와중에도 코드 리뷰를 해주겠다고 선뜻 도움의 손길을 내밀어주신 크루 분들께 감사의 말씀을 드립니다.  
  
많이 부족한 코드이지만, 고통스러워하면서도 즐겁게 코드를 짰으니 예쁘게 봐주시면 감사하겠습니다...ㅎㅎ  
리뷰를 받고 발전된 모습을 보여드릴 수 있으면 좋겠습니다!  
  
감사합니다!  

--------------------------

아래와 같은 우선 순위를 두고 과제를 진행했습니다:    

1. 기능 요구사항 
    - 요구하는 기능 전부 구현하기 
2. 프로그래밍 요구사항
    - 함수가 한 가지 일을 하도록 작게 구성하기 (15줄의 기준이 명확하지 않아, 함수의 시작 줄과 마지막 줄은 뺀 나머지 줄이라고 정의했습니다.)
    - 들여쓰기의 depth가 2를 넘지 않도록 주의하기
3. 과제 진행 요구사항
    - 구현하기 전 구현할 기능 목록을 최대한 자세하고 명확하게 작성하기 (기능 구현 중에 최대한 적게 수정하도록)
    - 기능 목록 단위로, Commit Message Conventions을 지키며 commit 하기  

### 기능 요구사항
우선, 제가 코딩 공부한 지 오래되지 않은 초보이고, 컨벤션을 모르고, 자바스크립트에 대한 이해도가 많이 떨어져, 구현하는 것에 우선 순위를 두었습니다. 처음에는 프로그래밍 요구사항에 맞춰 구현하려 했으나, 모듈에 대한 이해가 없다 보니 원칙에 맞지 않아 돌아가지 않는 코드를 짜게 되었습니다. 그래서 모듈에 관해서 공부하자니 시간이 촉박하여 우선 구현부터, 즉 돌아가는 코드부터 짜고, 나중에 고치자라는 생각으로 구현했습니다.  (~~그래서 초반 코드가 많이 혼란스럽습니다...ㅎ~~)   

### 프로그래밍 요구사항
구현에만 집중하다 보니 초반에는 코딩 컨벤션에도 맞지 않고, 이상한 이름을 가진 함수와 변수들이 많았습니다. 그걸 고치고자, 3기분들 코드를 참조하여 eslint와 prettier를 사용했습니다. 최대한 이름에서 무슨 일하는 함수인지, 변수인지 들어내기 위해 이름을 줄이지 않았습니다. 함수를 작게 구성하기 위해 기능 목록을 작성할 때, 기능의 조건들을 최대한 세분화해서 쓰려고 노력했습니다. 그렇게 하다 보니 신경 쓰지 않아도 들여쓰기의 depth이 2를 넘지 않고, 함수의 길이도 15줄을 넘지 않았습니다. 구현하기 바빠 많이 신경 쓰지도 못했는데 자연스럽게 되어있다니! 전에는 그렇게 코드를 간결하고 짧게 쓰려고 해도 안 되던 것이 되어 참 신기한 경험이었습니다.  

### 과제 진행 요구사항  
기능 목록을 작성하면서 저에게 작은 목표 하나가 있었습니다. 바로 처음 작성할 때 자세하고 명확하게 작성하여, 기능 구현 중에 최대한 적게 수정하는 것이었습니다. 초반에 작성했을 때는 이 정도면 수정할 일이 적겠지 싶었는데, 역시나, 코드를 적다 보니 계획과 다른 부분들이 있어 많이 수정했습니다. 비록 저의 목표를 달성하지 못했지만, 기능 구현 목록을 작성하는 것이 구현 시간을 크게 단축시켜 준다는 것을 깨달았습니다. 저는 만들고 싶은 것이 있다면 만들고 싶은 마음이 앞서 코드부터 작성하는, 이른바 무지성 개발을 해와 구현하기 바빠서 어떤 기능들을 어떻게 구현하려고 했는지 잊어버리거나, 구현 단계에서 계획을 같이하느라 기능을 다 구현하기도 전에 지쳐버려서 구현을 포기해 버리는 일들이 있었습니다. 그러나 계획을 짜 어떤 것을 구현할 것이며, 그것을 어떻게 구현할지 정리한 목록이 있으니 목표와 목적을 잊지 않고, 오로지 구현에만 집중할 수 있어 전보다 완성도를 많이 끌어올릴 수 있었습니다.   

또한 기능 단위로 커밋하는 것도 처음 해보고, 커밋 메세지도 컨벤션이 있다는 것을 처음 알아 적용하게 되었는데, 개인적으로 "아, 커밋은 이러려고 있는 것이구나"를 깨닫게 되는 귀중한 경험이였습니다. 항상 코드부터 쭉 짜고, 하루가 마무리 될 때쯤에 깃허브 저장용으로 커밋을 날려 커밋은 그저 저장하려고 쓰는 메세지의 용도로만 이해하고 있었는데, 커밋을 기능 단위로, 타입에 맞춰 어떤 것을 변경/추가 했는지 적으니 협업할 때도, 나중에 코드를 볼 때도 커밋 로그만 보면 무엇을 어떻게 변경했는지 일목요연하게 볼 수 있어 남에게도 나에게도 도움이 되는 참 좋은 기능이라는 것을 깨달았습니다.  

### 결론
비록 짧은 시간이지만, 과제를 풀면서 제가 많이 성장했다는 것을 체감하고 있습니다. 주마다 과제를 풀면서 하루가 다르게 성장해나갈 제 자신이 기대됩니다. 이런 좋은 기회 놓치지 않고, 선의에 성장으로 보답할 수 있도록 노력하겠습니다. 감사합니다!

2021-12-01 12:32 UTC, devhyun637 requested changes
안녕하세요 무님! 
저는 프론트엔드 3기 티케입니다:)
이게 어쩔수없이 본래 프리코스 기간을 지나고나서 리뷰를 해야한다는 생각에 리뷰가 늦었습니다 🥲

자신이 한 프로젝트에 대해서 이렇게 느낀점을 길게 PR에 남겨주시다니..⭐️ 너무 멋있으세요!
제가 큰 도움이 될지는 모르겠지만, 일단 최선을 다해서 프리코스의 기억을 되살리며 리뷰를 하였습니다.
저는 당시 피드백 받았던 내용과, 제가 생각하기에 '이정도면 지금 충분해.'라는 마음으로 리뷰를 했습니다.
더 심화된 내용을 기대하셨다면 다른 사람들의 코드리뷰도 함께 봐주시면 좋을 것 같아요🙏

세세한 리뷰는 아래 코멘트를 참고해주시고, 전반적인 PR에 대한 저도 회고를 한번 해보려고 합니다.
아! 회고에 대해서 아실지는 모르겠지만, 이렇게 PR에 남겨주신 것처럼 프로젝트에 대한 느낀점 또는 배운점을 정리한 것을 '회고'라고 불러요. 앞으로 코딩을 하면서 계속 이렇게 자신을 되돌아보는 거 매우 중요하다고 저는 생각해요(가끔은 놓치고있지만 저도 매일 하려고합니다 ㅎㅎ)

> 기능 요구사항
> 요구하는 기능 전부 구현하기

너무 좋습니다 👍

> 프로그래밍 요구사항
> 함수가 한 가지 일을 하도록 작게 구성하기 (15줄의 기준이 명확하지 않아, 함수의 시작 줄과 마지막 줄은 뺀 나머지 줄이라고 정의했습니다.)
> 들여쓰기의 depth가 2를 넘지 않도록 주의하기

음 대부분 함수가 한가지 일을 하도록 구현을 잘 해주셨는데, 15줄이라는 기준에 맞추려다보니깐 띄어쓰기를 전혀 안해주셔서 읽는데 가독성이 크게 좋지는 않았습니다. 공백도 컨벤션과 가독성에 큰 영향을 미치는데, 이를 위해서 함수의 역할을 더 분리해보는 연습을 해보아도 좋을 것 같아요! 대체적으로 네이밍도 그렇고 좋았습니다!

> 과제 진행 요구사항
> 구현하기 전 구현할 기능 목록을 최대한 자세하고 명확하게 작성하기 (기능 구현 중에 최대한 적게 수정하도록)

기능 요구사항 목록을 최대한 자세히 써주셨네요 👍 의문점은 왜 코드블럭으로 감쌌는지가...궁금합니다ㅎㅎ
또 저는 그때그때 기능을 한것마다 체크하기 위해서 체크박스로 만들고 계속 Readme 파일을 업데이트 하는 식으로 미션을 했던 것 같아요. 요구사항이 바뀔 수도 있고, 제가 생각한게 처음과 다를 수도 있으니깐요! 살아있는 문서화를 하기위해 노력해보아요!

> 기능 목록 단위로, Commit Message Conventions을 지키며 commit 하기

오 영어로 커밋을 써주셨군요! 좋습니다ㅎㅎ 커밋이 일단 많아서 꼼꼼히 하셨다는 걸 알 수 있었어요!
어떤 컨벤션을 사용하셨는지가 궁금하네용. 이것도 한번 공유해주시면 좋을 것 같습니다 :)
조금은 아쉬운 점은 `add error case`와 같은 건 너무 추상적이지 않을까 하는 생각이 들었어요. 어디서의 에러 케이스인거지? 이런 의문이랄까요

회고 중에서 이런 문구가 있는데
> 구현에만 집중하다 보니 초반에는 코딩 컨벤션에도 맞지 않고, 이상한 이름을 가진 함수와 변수들이 많았습니다. 그걸 고치고자, 3기분들 코드를 참조하여 eslint와 prettier를 사용했습니다. 

++
질문이 있습니다.
`eslint`와 `prettier`의 역할과 함수와 변수명에 대한 연관성을 잘 모르겠다는 생각이 들었습니다 :)
무님이 공부하신 `eslint`와 `prettier`의 역할은 무엇일까요?

+++
저도 프리코스에서 마르고 닳도록 읽었던, 포비의 글인데 함께 추천합니다! https://brunch.co.kr/@javajigi/8

2021-12-01 12:32 UTC, devhyun637 commented on index.html
> +        <input type="number" id="user-input" />
👍👍👍 
저는 처음 프리코스 할 때 input의 타입을 바꿀 생각을 하지 못했는데 대단하시네요!

2021-12-01 12:32 UTC, devhyun637 commented on index.html
>          <button id="submit">확인</button>
button 태그의 [default type](https://developer.mozilla.org/ko/docs/Web/HTML/Element/button#attr-type)이 무엇일까요?

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +    let num = MissionUtils.Random.pickNumberInRange(MIN_NUMBER, MAX_NUMBER);
`MissionUtils`이 뭔가했더니.. 제공하는 라이브러리 함수였군요 👍

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +const randomComputerInputNumber = () => {
줄이지 않고 이름을 통해 의도를 드러내려고 노력했다는 점에서는 매우 좋습니다 👍👍
하지만, 함수명이 명확하게 느껴지지 않는 것 같아요.
이 함수의 코드를 읽어보니 '랜덤 숫자를 생성한다.'인 것 같은데 좀 더 명확하게 수정해보는 걸 어떨까요?

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +    }
중복된 숫자가 없도록 하기 위해서 이 방법을 쓰셨군요 👍
하지만 역할이 과연 이 함수가 알아야하는 것인지 고민해보면 좋을 것 같습니다.

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +  return computerInputNumber;
함수가 15줄 이하로 가야한다고 해서 모든 공백을 없앤 것 같은데, 
함수의 '역할'의 측면에서 좀 더 고민해보고 공백을 적절히 활용하는 것도 좋은 방법일 것 같아요:)
개인적인 취향이겠지만, 저는 보통 return 앞에는 공백을 두는 편입니다

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +  localStorage.setItem("computerInputNumber", computerNumber);
와우! localStorage를 사용하셨어요! 👍👍👍
저의 과거를 생각해보면 저는 첫 미션때 이런 방법을 활용할줄도 몰랐었던거 같은데 대단하십니다!

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +  return localStorage.getItem("computerInputNumber");
흠 만약에 localStorage에 `computerInputNumber` key가 없다면 어떻게 될까요?

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +  let [ball, strike] = [0, 0];
구조분해할당이라니 너무 멋집니다 👍

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +  result.textContent = "";
가독성을 위해 변수 선언과 활용 부분을 나눠보는 건 어떨까요?

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +      userInput.value = "";
이건 저도 레벨이 좀 지나고 나서 UX라는 것을 고려할 때 느낀거라서 지금은 그냥 이런것도 고려하는구나~ 라고 생각하시고 넘어가면 좋을 것 같아요! (그냥 제가 드리는 보너스 팁 🧚‍♀️)

내가 입력한 숫자가 잘못되었다고해서 input을 지워버리면, 사용자는 자신이 입력한 '잘못된' 숫자를 확인할 기회를 놓쳐버리게 되지 않을까요? 지우는 역할을 프로그램이 가지고 있어야하는지 아니면 사용자가 가지고 있어야하는지 고민해보면 좋을 것 같아요!

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +    restartButton.onclick = restart;
밑에있는 `getUserInput`함수는 addEventListener를 사용하셨는데, 여기는 왜 이벤트등록을 이렇게 했을까용?

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +export default function BaseballGame() {
어디에 보내시려구요 🥲 누구를 위한 export 일까요

2021-12-01 12:32 UTC, devhyun637 commented on src/index.js
> +new BaseballGame();
왜 `new` 연산자를 사용하셨을까요?

2021-12-01 12:32 UTC, devhyun637 commented on src/constants.js
> +};
와! 상수화를 하셨네요! 👍👍👍👍
좀 더 가독성 좋은 코드를 위해서, 공통된 것들끼리 묶어서 분리를 해보는 것도 추천드립니다

2021-12-01 12:32 UTC, devhyun637 commented on src/check_valid.js
> +  return [...new Set(userInput)].length !== MAX_LENGTH;
👍

2021-12-01 13:23 UTC, veggie-garden commented on index.html
> +        <input type="number" id="user-input" />
앗 다른 분의 코드를 보고 배운 것입니다...ㅎㅎ 그래도 칭찬 감사합니다!

2021-12-01 13:29 UTC, veggie-garden commented on index.html
>          <button id="submit">확인</button>
버튼의 type이 submit 이라도 매번 작성해야 하나요? 작성하지 않으면 type은 기본값 submit으로 지정한다고 문서에 써져 있어, submit이 아닌 다른 타입일 때 작성하면 된다고 생각했는데 하는 것과 안 하는 것의 차이가 있나요?

2021-12-01 13:32 UTC, veggie-garden commented on src/index.js
> +const randomComputerInputNumber = () => {
generateRandomComputerInputNumber 혹은 generateRandomComInputNum 이런 식으로 함수명을 지으면 될까요? 두번째 함수명처럼 Computer => Com 으로, Number => Num으로 줄여도 되나요?

2021-12-01 13:40 UTC, veggie-garden commented on src/index.js
> +  return computerInputNumber;
저는 저렇게 공백 없이 함수를 작성하는 것이 익숙해 그렇게 썼는데, 다른 분들이 보시기에 가독성이 좋지 않은 코드로 보일 수도 있군요... if문이나 while문 이전에 공백을 하나씩 삽입하는 것도 가독성을 높일 수 있나요? 혹시 참고할만한 가독성 좋은 코드가 있으시면 알려주실 수 있나요..? 가독성 높은 코드란... 어렵네요..ㅠㅠ

2021-12-01 13:41 UTC, veggie-garden commented on src/index.js
> +  localStorage.setItem("computerInputNumber", computerNumber);
어디서 들었는데 전역변수를 사용하는 것이 안 좋다고 들어 localStorage를 사용했습니다...ㅎㅎ 칭찬 감사합니다...ㅎㅎ

2021-12-01 13:52 UTC, veggie-garden commented on src/index.js
> +  return localStorage.getItem("computerInputNumber");
어... 페이지가 로드될 때마다 `init` 함수가 실행되고 그 안에 `saveRandomComputerInputNumber` 함수가 돌아갑니다. 이 함수는 랜덤 숫자를 생성하는 함수를 실행해서 그 리턴 값을 localStorage에 저장하기 때문에 `computerInputNumber` key가 없을 리가 없다 생각했는데 그런 경우가 발생할 수도 있나요?

2021-12-01 13:52 UTC, veggie-garden commented on src/index.js
> +  let [ball, strike] = [0, 0];
앗... 저것도 보고 배운 것이라서.... 칭찬 감사합니다..ㅎㅎㅎㅎ

2021-12-01 13:54 UTC, veggie-garden commented on src/index.js
> +  result.textContent = "";
아 저런 부분도 가독성을 해치는군요...! 수정하겠습니다!

2021-12-01 13:56 UTC, veggie-garden commented on src/index.js
> +      userInput.value = "";
실은 저도 그 부분을 생각해보긴 했는데 나중에는 그런 부분까지 고려해야 하는군요! 팁 감사합니다!

2021-12-01 14:01 UTC, veggie-garden commented on src/index.js
> +    restartButton.onclick = restart;
addEventListener를 사용하면 15 줄이 넘어가서 저런 방식으로 했습니다! 혹시 이런 것도 문제가 되나요? 코드 통일성을 해쳐서 그런 건가요?

2021-12-01 14:08 UTC, veggie-garden commented on src/index.js
> +export default function BaseballGame() {
저도 모르겠어요...ㅠㅠ 프로그래밍 요구사항에서 저런 식으로 사용하라고 되어있어서 사용했는데 실은 왜 export default function을 쓰는지 모르겠어요... 프로젝트가 방대해지면 함수들을 다른 파일에 분리하기 위해서 모듈을 쓴다고 이해했습니다. 다른 js 파일들은 index.js에 import 하기 위해 export을 사용하는 것이 이해가 되는데, index.js 같은 경우는 export default function BaseballGame() 이 무엇을 의미하는지, 무슨 일은 하는지 잘 모르겠어요. 이런 경우에는 무엇을 공부해야 할까요...?

2021-12-01 14:41 UTC, veggie-garden commented on src/index.js
> +new BaseballGame();
다른 분들의 코드를 보니 new를 쓰셨고, new를 안 쓰면 test에서 fail이 떠서 사용했습니다!

new를 사용했을 때:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/63505022/144254259-0a18136a-125b-488a-bee1-affbb0a9f62e.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/63505022/144254149-af28b6c6-cef6-499a-aefd-634ce631acb1.png">

new를 사용하지 않았을 때:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/63505022/144254367-00f2854e-e83e-4a07-99bc-e28f50fb75e0.png">
<img width="584" alt="image" src="https://user-images.githubusercontent.com/63505022/144254452-8a930b89-b391-431f-ba1e-a21f764b7ed5.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/63505022/144254487-0a129196-80a5-45cb-b14e-83d5fc392900.png">

2021-12-01 14:49 UTC, veggie-garden commented on src/constants.js
> +};
`const num = {
  min: 1,
  max: 9,
  len: 3,
};

export { num }; `

이런 식으로 하는 것을 말씀하시는 건가요? eslint가 https://github.com/import-js/eslint-plugin-import/blob/v2.25.3/docs/rules/prefer-default-export.md 이런 식으로 하는 것이 좋다고 해서 저렇게 했는데 위의 방법처럼 해도 되는 건가요?

2021-12-01 15:23 UTC, veggie-garden commented
티케님 안녕하세요!

저의 이 길고 긴... 고해성사 같은 회고와 코드들을 꼼꼼히 봐주셔서 감사합니다! 

> 공백도 컨벤션과 가독성에 큰 영향을 미치는데, 이를 위해서 함수의 역할을 더 분리해보는 연습을 해보아도 좋을 것 같아요! 대체적으로 네이밍도 그렇고 좋았습니다!

공백도 컨벤션이라니 몰랐네요. 가독성을 높이기 위해서 노력하겠습니다! 대체적으로 좋았다니 좋게 봐주셔서 감사합니다. 

> 의문점은 왜 코드블럭으로 감쌌는지가...궁금합니다ㅎㅎ

탭을 쓰니까 자동으로 코드블럭으로 감싸지더라고요...? 불렛 포인트로 바꾸려다가 이게 좀 더 보기 좋은 거 같아서 내버려두었는데 생각해보면 코드블럭은 코드를 위해서 있는데 불렛 포인트를 쓰는게 취지에 더 맞다는 생각이 드네요. 수정하도록 하겠습니다!

> 또 저는 그때그때 기능을 한것마다 체크하기 위해서 체크박스로 만들고 계속 Readme 파일을 업데이트 하는 식으로 미션을 했던 것 같아요. 요구사항이 바뀔 수도 있고, 제가 생각한게 처음과 다를 수도 있으니깐요! 살아있는 문서화를 하기위해 노력해보아요!

체크박스...! 체크박스를 사용하면 진도가 어디까지 나갔는지 확인할 수 있으니 훨씬 좋겠네요. 다음에는 저도 체크박스를 활용해보도록 하겠습니다. 한 번에 완벽한 문서를 작성하는 것은 불가능한 것이죠. 제가 너무 욕심을 냈네요. 살아있는 생생한 문서를 작성하기 위해 저도 노력하겠습니다!

> 오 영어로 커밋을 써주셨군요! 좋습니다ㅎㅎ 커밋이 일단 많아서 꼼꼼히 하셨다는 걸 알 수 있었어요!

과제를 올려주신 코치 분...? (호칭을 어떻게 해야 할지 모르겠네요) 그 분이 영어로 커밋을 남기신 것을 보고 영어로 작성했습니다! 커밋을 영어로 하는 것이 좋을까요 아니면 한국어로 하는 것이 좋을까요? 저는 커밋이 너무 많아서 혼란스럽지는 않은가 걱정했는데 꼼꼼히 했다는 것으로 보여서 다행이네요.

> 어떤 컨벤션을 사용하셨는지가 궁금하네용.

README.md에 적혀있는 대로, [AngularJS Commit Message Conventions](url) 참고해 commit log를 남겼습니다!

> 조금은 아쉬운 점은 add error case와 같은 건 너무 추상적이지 않을까 하는 생각이 들었어요. 어디서의 에러 케이스인거지? 이런 의문이랄까요

아하... 그럼 commit에 파일명을 적어도 될까요? 예를 들자면 "chore: add error case - check does user input include zero or not in constants.js" 같이요

> eslint와 prettier의 역할과 함수와 변수명에 대한 연관성을 잘 모르겠다는 생각이 들었습니다 :)
무님이 공부하신 eslint와 prettier의 역할은 무엇일까요?

아, eslint로 컨벤션을 지정하고 prettier로 코드를 보기 좋게 만들기 위해서 사용했다는 뜻이였어요. 이상한 이름을 가진 함수와 변수들은 eslint, prettier와 상관 없습니다. Eslint와 prettier을 공부한 글이 있는데 여기에 첨부하겠습니다! https://veggie-garden.tistory.com/13

> 저도 프리코스에서 마르고 닳도록 읽었던, 포비의 글인데 함께 추천합니다!

저도 전에 그 글을 봤는데 마르고 닳도록 봐야지 프리코스 합격하는 것인가요...! 저도 합격을 위해서 마르고 닳도록 봐야겠습니다. 공유 감사드려요!

2021-12-02 01:56 UTC, devhyun637 commented on index.html
>          <button id="submit">확인</button>
앗 이부분은 제가 id를 type으로 잘못본 것 같습니다 :) 정정하겠습니다

2021-12-02 01:58 UTC, devhyun637 commented on src/index.js
> +const randomComputerInputNumber = () => {
일단 코드를 작성할 때 일관성이 중요하다고 생각하는데, 동사가 먼저 나오는 형태로 보통 함수명을 지으니 다른 함수들과 통일성을 유지하면 어떨까해서 남긴 리뷰입니다.

1. 생성한다의 generate가 먼저 나오는 것 좋습니다.
2. 컴퓨터가 input을 하는지에 대해서 고민을 해보면 더 깔끔한 이름이 나올 것 같습니다.
3. num, com 등은 앞서 언급드린것처럼 다른 부분과 통일성만 맞추면 뭐든 상관없을 것 같습니다.

2021-12-02 02:00 UTC, devhyun637 commented on src/index.js
> +  return computerInputNumber;
사실 가독성도 그렇고, 남이 읽기에 좋은 코드란 제가 익숙한 코드이기때문에 이거는 그냥 무님이 계속 다른 분들 코드보면서 잘 읽히는 것이 무엇인지 보면 좋을 것 같아요! 공백이 있다고 해서 무조건 가독성이 좋은 것도, 혹은 공백이 없다고 해서 가독성이 나쁜건 아니니깐요!
저는 이 함수가 어떤 값을 return 하는지 바로 파악하기 위해서 앞부분을 띄는 습관을 들인건데 이 부분에 대해서도 공감이 안가신다면 안하셔도 되는 겁니다 :) 

> if문이나 while문 이전에 공백을 하나씩 삽입하는 것도 가독성을 높일 수 있나요?

저는 보통 그렇게 생각해서 공백을 삽입합니다 :)

2021-12-02 02:08 UTC, devhyun637 commented on src/index.js
> +  return localStorage.getItem("computerInputNumber");
제가 초반에 했던 생각과 매우 비슷하네요 :) 
프로젝트를 짜면서 `제대로 동작을 했다면` 절대 제가 말한 것처럼 오류상황이 일어날 수 없지요. 하지만 프로그램도, 브라우저도 어떠한 이유에서 개발자도, 사용자도 모르는 어떤 형태의 오류가 날 수 있다는 걸 늘 생각해야할 것 같아요. 내가 이렇게 짰으니 절대 오류가없어! 라기보다는 예측할 수 없는 에러를 모두 방지할 수 있는, 최대한 `방어적인` 코드를 짜는 방법을 저는 추천합니다. 

추가적으로 key값은 모두 상수화 처리를 해주는 것을 추천합니다. 그 이유는 무엇일까요? 👀

2021-12-02 02:08 UTC, devhyun637 commented on src/index.js
> +    restartButton.onclick = restart;
통일성때문에 여쭤보았던 겁니다!

2021-12-02 02:15 UTC, devhyun637 commented on src/index.js
> +export default function BaseballGame() {
음 아주 쉽게 각각의 자바스크립트 파일이 하나의 모듈이라고 생각해볼게요. 그리고 여러개의 모듈이 있을 때 서로 필요한 부분을 주고받으려면 export를 통해서 내보내고 import를 통해서 다른 모듈에 있는 것을 받아서 쓰는 것이지요. (아주 간단하게만 설명했습니다.)

제가 드린 리뷰의 의도는 BaseballGame을 다른 모듈에서 사용하고 있는 걸까요? 를 고민해보라는 뜻에서 남겼습니다.

[MDN module](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Modules)
[MDN import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
[MDN export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export)

2021-12-02 02:15 UTC, devhyun637 commented on src/index.js
> +new BaseballGame();
아 미션의 조건이었군요. new 키워드도 이참에 공부해보면 좋을 것 같아요!

2021-12-02 02:16 UTC, devhyun637 commented on src/constants.js
> +};
파일을 분리하는 방법도 있겠죠? 정답은 없고 방법은 많을 것 같습니다 :)

2021-12-02 02:17 UTC, devhyun637 commented
코멘트에 대한 답변 달았습니다. 적용된 커밋이 이후에 없네요! 
이대로 리뷰를 마감해달라는 의미일까요?👀

그리고 읽은 댓글에 코멘트로 아무 이모지나 달아주시면 제가 댓글이 없어도 확인했다는 걸 쉽게 볼 수 있을 것 같습니다.
빠른 답변 감사합니다:)

2021-12-02 08:57 UTC, veggie-garden commented on src/index.js
> +    }
혹시 무슨 말씀이신지 더 풀어서 설명해주실 수 있나요? 무슨 뜻인지 잘 모르겠습니다.

2021-12-02 09:05 UTC, veggie-garden commented on src/index.js
> +  return computerInputNumber;
그렇군요... 앞으로 가독성을 높이기 위해서 노력하겠습니다. 조언 감사합니다!

2021-12-02 09:08 UTC, veggie-garden commented on src/index.js
> +  return localStorage.getItem("computerInputNumber");
아하... 그래서 그렇군요...! 항상 발생 가능한 모든 오류 상황에 대비할 수 있게끔 코드를 짜도록 노력해야겠어요! 상수화는 나중에 key의 이름이 변경될 수도 있어서 constants.js 에 저장하면 나중에 찾아 변경하기 쉽기 때문일까요?

2021-12-02 10:39 UTC, veggie-garden commented on src/index.js
> +const randomComputerInputNumber = () => {
아하 함수명도 코드의 일관성에 영향을 끼치는군요... 개발자가 이름 짓는 것을 제일 어려워한다는 짤을 보았는데 통일성 있으면서도 무슨 일을 하는지 단번에 알아 볼 수 있으며 깔끔한 이름을 만드는 것이 생각보다 어렵네요..ㅎㅎ 조언대로 수정하도록 하겠습니다!

2021-12-02 11:02 UTC, veggie-garden commented on src/index.js
> +    restartButton.onclick = restart;
아하... 이런 작은 부분들까지 영향을 끼치다니... 수정하겠습니다!

2021-12-02 11:03 UTC, veggie-garden commented on src/index.js
> +new BaseballGame();
네, 알겠습니다! 공부해보겠습니다.

2021-12-02 11:04 UTC, veggie-garden commented on src/constants.js
> +};
아 그런 방법이! 파일을 분리해도 좋겠네요.

2021-12-02 11:35 UTC, veggie-garden commented on src/index.js
> +export default function BaseballGame() {
export default function을 쓰는 건 test를 돌려보기 위해서 있는 거라고 생각했는데 지금 해보니 있으나 없으나 상관이 없네요. 흠... 왜 그런 건지 나중에 공부를 더 해봐야겠습니다.

2021-12-02 11:40 UTC, veggie-garden commented
여기서 리뷰를 종료해달라는 의미가 아니라 글만 써놓고 코드를 수정하지 못 해서 그냥 두었던 것이였어요...! 답이 늦어졌네요...ㅠㅠ 죄송합니다. 

리뷰는 정답을 주는 것이 아니라 정답까지 갈 수 있도록 길을 이끌어주는 것이라 생각해서 힌트를 주시는 것만으로도 충분합니다! 독학할 때는 힌트조차 줄 수 있는 사람이 없어서 이정도로만도 감지덕지합니다. 지금 당장 이해가지 못 하는 부분은 티케님 말대로 기술부채로 남겨놔야겠어요!

정성스런 답변 감사합니다!

2021-12-03 01:29 UTC, devhyun637 commented on src/index.js
> +    }
랜덤숫자를 생성하는 함수 안에서 while문을 통해 중복되는 숫자가 없는지 있는지를 파악하고 있습니다.
이 중복되는 숫자가 있는지 없는지를 파악하는게 과연 이 함수가 알아야하는지를 생각해보면 더 작게 함수를 쪼개볼 수 있을 것 같아요 :)

2021-12-03 01:38 UTC, devhyun637 commented
안녕하세요 무님 :) 티케입니다!
다음 미션을 하러 갈 시간이군요 :) 아마 다음번 미션에는 새로운 분이 리뷰를 남겨주실수도 있을 것 같아요!
저는 프리코스 미션 마감시간 이후에 리뷰를 남기도록 하겠습니다! 더빡센 리뷰를 하기를 원한다면 '동동'이라는 크루를 소개해드릴게요ㅋㅋㅋ

보통 커밋메세지는 짧지만, 의미를 알아볼 수 있도록 작성하는데 영어로 그게 힘들다면 한글로 먼저 작성하는 것도 추천합니다. 저는 파일이름은 안쓰기는 해요! 저번에 `add error case` 같은 경우에는 0일때의 에러 케이스라면 `숫자가 0일경우 에러핸들링 추가` 이런식으로 쓰는 편인데 이건 사실 개인 취향이라서 본인이 많이 써보면 도움이 될 것 같아요!
블로그의 정성스러운 정리 덕에 저도 공부가 되네요!!

마지막 이해가 잘 안가신다는 부분에 대해서만 확인하시면 close 하겠습니다 :)

2021-12-03 01:40 UTC, devhyun637 commented on src/index.js
> +const randomComputerInputNumber = () => {
수정한 다음에, 저는 항상 커밋에서 오른쪽 버튼을 눌러서 `링크주소복사`를 해서 붙여넣는 편이에요!
이번에는 제가 보기 편할라고 넣겠습니다 ㅎㅎ https://github.com/REVENGE-WOOTECO/javascript-baseball-precourse/pull/5/commits/d9ec4517ec99cd63c64e61e4732ac7430a73e56d

2021-12-03 01:48 UTC, devhyun637 commented
무님 코드리뷰 반영
함수네이밍 변경 https://github.com/REVENGE-WOOTECO/javascript-baseball-precourse/pull/5/commits/d9ec4517ec99cd63c64e61e4732ac7430a73e56d
상수화된 변수 객체로 묶기 https://github.com/REVENGE-WOOTECO/javascript-baseball-precourse/pull/5/commits/538c1efc0a5a7e1a7ff838a73ee9f042ec83f0dc, https://github.com/REVENGE-WOOTECO/javascript-baseball-precourse/pull/5/commits/93974a3fb4d1464c9d65ed6d22379a4d83dcb949, https://github.com/REVENGE-WOOTECO/javascript-baseball-precourse/pull/5/commits/64cd2544b412247b2bffdae851ffe8eed557114d
로컬스토리지 에러핸들링 추가, 초기화 함수에 input 비워주는 기능 추가, 이벤트핸들러 코드방식 변경, 결과 출력 함수의 조건문 수정(저는 개인적으로 이렇게 모든걸 다 넣어버리는 커밋 안좋아합니다.. 커밋 수가 늘어나는 것보다 이 커밋의 의미가 사라지는 걸 더 안좋아하는편..) : https://github.com/REVENGE-WOOTECO/javascript-baseball-precourse/pull/5/commits/53942eb4e6305f8eb77c2de2ddb72225bbf701c1 
README 파일 업데이트 : https://github.com/REVENGE-WOOTECO/javascript-baseball-precourse/pull/5/commits/f3a4bafd9a548df63359de1009e4a51e96c49fda
이벤트핸들러 등록부분 수정 (이건 fix겠네요) : https://github.com/REVENGE-WOOTECO/javascript-baseball-precourse/pull/5/commits/656b6ef9ae3d6af20a64e5cd60528fc4a02e341a




원래는 개개의 커밋마다 어떻게 수정되었는지 반영할 때 이렇게 정리하는 편인데 제가 무님이 어떤 것을 고쳤는지 한눈에 보기 위해서 그냥 정리했습니다! 모든 코드리뷰를 볼때 그래야하겠지만, 저도 제 개인적인 의견과 취향이 듬뿍담긴 코드리뷰이니 `정답은 절대 없다`를 염두하시고 무님이 옳다고 생각하는 부분은 무시하고, 저와 의견이 동일하다면 받아들이시면 될 것 같아요!

2021-12-03 04:15 UTC, veggie-garden commented on src/index.js
> +    }
함수를 더 작게 쪼개보려고 했는데 오히려 더 작게 쪼개는 것이 코드가 더 복잡해지는 것 같고, while문을 두 번 돌리는 것 때문에 그렇게 하라고 하시는 것 같아서 while문 안에 if문을 넣는 방식으로 수정했습니다. 의도하신 바를 제가 잘 파악했는지 모르겠네요. 그리고 while문 전에 let num을 먼저 생성하여 while문이 돌 때마다 num에 값을 할당하는 것이, while문이 돌 때마다 let num을 생성하는 것보다 메모리를 덜 사용할 것이라고 생각해서 이렇게 짰는데 이렇게 하는 것이 정말 메모리를 덜 사용하는 방법인가요? 으아 질문을 너무 많이 해서 번거롭게 해드리는 것이 아닌가 염려되네요. 항상 상세하게 답변해주셔서 감사합니다.

2021-12-03 04:41 UTC, veggie-garden commented
티케님! 

항상 정성스런 코드 리뷰 감사해요. 리뷰 남기실 때마다 내가 하는 말이 다 맞아! 이런 식으로 하는 것이 아니라, 배려심 넘치는 조언을 주시려고 하는게 느껴져서 리뷰 받을 때마다 감동받았습니다. 다만 제가 실력이 부족해서 아직은 무엇이 옳고 무엇이 좋은 건지 잘 모르겠어요. 그래서 해주신 조언 모두 마음 한 켠에 담아놨다가, 조금 더 성장했을 때 저한테 맞는지 안 맞는지 판별하려고 합니다! 일단 많은 조언을 듣는 것이 중요하다고 생각해서요ㅎㅎ 

커밋도 자세히 쓰는 것이 좋겠다라고 생각해 그렇게 썼는데 차라리 그 내용을 바디에다가 적는다든지 해서 짧게 쓰는 것이 좋겠네요. 헤더는 짧을 수록 의미가 있는 것이라는 걸 다시 일깨워주셔서 감사합니다! 

더 빡센 리뷰라니! 어우, 받을 수 있으면 정말 좋겠네요. 다만 제가 따라갈 수 있을지가 걱정입니다...ㅎㅎㅎ 

지금 면접 보시느라 정신 없다고 들었어요. 바쁘신 와중에도 정성스러운 코드 리뷰 해주셔서 감사합니다. 나중에 저도 티케님처럼 다른 사람들을 도울 수 있었으면 좋겠네요. 면접 후회없이 잘 보시고, 좋은 결과 있기를 바랍니다! 면접 파이팅이에요!!! 날이 추워지는데 건강 유의하시고, 코로나 조심하시고, 행복한 연말 보내세요. 감사합니다!

2021-12-03 13:01 UTC, devhyun637 commented on src/index.js
> +    }
코드를 더 작게 쪼갰는데 로직이 복잡해지는 경우가 무엇인지 궁금하네요 ! while문을 두번 사용하는 것 때문이라기보다는
`랜덤숫자를 생성한다.` 라는 역할을 가진 함수가 `중복된 숫자가 있는 지 없는 지 확인하는 로직`을 가지고 있어야하나? 라는 점에서 생각해보시라고 한겁니다 :)

메모리적 측면은 저도 잘 모르겠습니다 :) 헛헛ㅎㅎ 음 그래도 생각을 해보자면 당연히 while문을 돌때마다 변수를 생성하는게 더 많은 메모리를 차지하는건 맞겠죠? 하지만 뭐 1231283918273번 while문이 반복되는 건 아니니깐 무님이 프리코스 미션을 할 때에는 메모리와 같은 최적화부분보다는 어떻게하면 더 잘 읽히는 변수명, 함수명을 입력하고 함수의 역할을 명확하게 할 수 있을지를 고민하기를 추천합니다 :)

2021-12-03 13:07 UTC, devhyun637 approved these changes
무님! 

엄청나게 많은 대화를 나누었군요 :) 내적친밀감 가득하군요ㅎㅎㅎ
그리고 질문을 많이하는 것과 저에게 무님의 의견을 어필하는거 너무 좋습니다!!
어쩌면 제가 처음 우아한테크코스의 초기에 적극적이지 못했던 아쉬움을 무님이 대신 해주시는 것 같아서 저도 공부를 더 열심히해야겠다는 자극도 받고 너무 좋네요 :)

같이 취업준비하는 입장에서 마구마구 물어봐주시고 (꼭 제가 아니더라구요), 최대한 저희를 많이 괴롭혀주세요! 그리고 이해가 안가는 부분은 우테코 3기 크루들 말고도 단톡방이 있다고 들었는데, 거기서 ~한 리뷰를 받았는데 이해가 잘 안가는 것 같아요. 어떤 의도일까요? 또는 ~한 부분 저는 공감이 안되는데 다른 분을은 어떠세요? 라는 질문을 통해서 토론의 장으로 만들어보는 것도 좋을 것 같아요 👍 

야구게임은 이정도로 마무리하고, 이제 자동차경주로 넘어가서 제가 드린 조언들을 참고하여 코드를 짜면 좋을 것 같습니다:) 

이만 클로즈하겠습니다 :) 
그리고 단톡엔 제가 없지만, 연락할 길은 많으니 저한테도 궁금하신거 있으면 언제든 연락주세요! 
고생하셨습니다 ~!!!

2021-12-03 13:14 UTC, merged